#!/bin/bash
# Multi-Process E2E Runner (per-node gem5 split) — decoupled edition
#
# This launcher reads a fixed JSON topology config (configs/topo_1s.json or
# configs/topo_2s.json), generates the networksim topo.json, compiles the
# workload into a FIXED path (tests/e2e/workloads/workload.elf), starts all
# module processes per the JSON, waits for gem5 to finish, then invokes the
# independent verifier tests/e2e/verify.py.
#
# Usage:
#   bash tests/e2e/run_multi.sh [--1s|--2s] <tc> ... [<tc> ...]
#
# Default is --1s. Dual-socket TCs (32-35,39) require --2s; if you pass a
# dual-socket TC under --1s the script will auto-error.
#
# topology (*) is fixed in the JSON files; the networksim crossbar mesh is
# regenerated by scripts/gen_topo.py to match (NMOD depends only on topology).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
GEM5_BIN="$ROOT_DIR/gem5/build/ARM/gem5.opt"
UBIO_BIN="$ROOT_DIR/build/bin/ubio"
NSIM_BIN="$ROOT_DIR/build/bin/networksim"
TEST_E2E="$ROOT_DIR/tests/e2e/test_e2e.py"
WORKLOAD="$ROOT_DIR/tests/e2e/workloads/workload.elf"
TOPO_JSON="$ROOT_DIR/build/run/topo.json"
TIMEOUT_SEC="${TIMEOUT_SEC:-600}"

# ── Config selection ────────────────────────────────────────────────
TOPO_KIND="1s"
case "${1:-}" in
    --1s) TOPO_KIND="1s"; shift ;;
    --2s) TOPO_KIND="2s"; shift ;;
esac
JSON="$ROOT_DIR/configs/topo_${TOPO_KIND}.json"
[ -f "$JSON" ] || { echo "FATAL: config $JSON not found" >&2; exit 2; }

# ── Determine sockets + nmod from JSON ───────────────────────────────
read NUM_NODES NUM_SOCKETS < <(python3 -c "
import json
c=json.load(open('$JSON'))
print(c['num_nodes'], c['num_sockets'])
")
NMOD=$((NUM_NODES * NUM_SOCKETS))

# ── Per-TC fault-injection rules (ubio --fault-rules=...) ────────────
fault_rules_for_tc() {
    case "$1" in
        47) echo "tc47_dup_clear:ClearReq:1:0:0:dup::1" ;;
        48) echo "tc48_dup_inv_ack:InvalidateAck:2:0:0:dup::1" ;;
        49) echo "tc49_dup_inv_ack:InvalidateAck:1:0:0:dup::1" ;;
        *)  echo "" ;;
    esac
}

# ─── Lookup json module command (placeholder substitution) ────────────
# expand_cmd <module_id> <fault_rules> [node_outdir]
# Env: NODE_OUTDIR (used to substitute {node_outdir}; only meaningful for gem5_*)
expand_cmd() {
    local mod_id="$1"; local frules="$2"; local node_od="${3:-}"
    NODE_OUTDIR="$node_od" python3 - "$JSON" "$mod_id" "$frules" <<'PY'
import json, os, sys
cfg_path, mod_id, frules = sys.argv[1], sys.argv[2], sys.argv[3]
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(cfg_path)))
c = json.load(open(cfg_path))
mod = next((m for m in c["modules"] if m["id"]==mod_id), None)
if not mod:
    sys.exit(2)
def r(s):
    s = s.replace("{root}", ROOT)
    s = s.replace("{gem5_bin}", os.path.join(ROOT,"gem5/build/ARM/gem5.opt"))
    s = s.replace("{ubio_bin}", os.path.join(ROOT,"build/bin/ubio"))
    s = s.replace("{nsim_bin}", os.path.join(ROOT,"build/bin/networksim"))
    s = s.replace("{test_e2e}", os.path.join(ROOT,"tests/e2e/test_e2e.py"))
    s = s.replace("{workload}", os.path.join(ROOT,"tests/e2e/workloads/workload.elf"))
    s = s.replace("{topo_json}", os.path.join(ROOT,"build/run/topo.json"))
    s = s.replace("{node_outdir}", os.environ.get("NODE_OUTDIR",""))
    s = s.replace("{fault_rules_args}", frules)
    return s
print(r(mod["cmd"]))
PY
}

# ─── per-TC run ─────────────────────────────────────────────────────
LOG_BASE="$ROOT_DIR/logs/$(date +%Y%m%d_%H%M%S)_${TOPO_KIND}"
mkdir -p "$LOG_BASE" "$ROOT_DIR/build/run"

# Kill any leftover infra from a previous TC / abort.
_kill_infra() {
    pkill -9 -f "gem5.opt.*test_e2e" 2>/dev/null || true
    pkill -9 -f "/build/bin/ubio" 2>/dev/null || true
    pkill -9 -f "/build/bin/networksim" 2>/dev/null || true
    for pid in ${UBIO_PIDS:-} ${NSIM_PID:-}; do
        kill -9 $pid 2>/dev/null || true
    done
    wait 2>/dev/null || true
    sleep 0.3
    UBIO_PIDS=""; NSIM_PID=""
}
trap '_kill_infra' EXIT

run_tc() {
    local tc=$1
    _kill_infra  # ensure clean state before each TC

    local m5base="$ROOT_DIR/build/run/tc${tc}"
    local m5outdir="$m5base/m5out"
    rm -rf "$m5base"; mkdir -p "$m5outdir"

    echo ""
    echo "=== TC${tc} (topo=$TOPO_KIND, ${NUM_NODES}nodes x ${NUM_SOCKETS}sockets) ==="

    # 1. Compile workload → fixed path workload.elf
    bash "$ROOT_DIR/scripts/compile_workload.sh" "$tc" >/dev/null 2>&1 \
        || { echo "  TC${tc} COMPILE FAILED"; return 1; }

    # 2. Generate networksim topo.json (fixed mesh by topology kind)
    python3 "$ROOT_DIR/scripts/gen_topo.py" --type "$TOPO_KIND" --out "$TOPO_JSON" >/dev/null 2>&1
    # Clean sshd ipc endpoints
    rm -rf /workspace/gem5/shared_ipc/ipc_* /tmp/ubio_n* /tmp/networksim_* 2>/dev/null || true
    mkdir -p /workspace/gem5/shared_ipc 2>/dev/null || true

    # 3. Start networksim (must bind before ubio connects)
    local nsim_cmd
    nsim_cmd="$(expand_cmd networksim '')"
    echo "[launch] networksim (NMOD=$NMOD)"
    eval "$nsim_cmd" >"$LOG_BASE/nsim_tc${tc}.log" 2>&1 &
    NSIM_PID=$!
    sleep 1

    # 4. Start N gem5 nodes, wait until each binds its ports (STEP5 marker)
    GEM5_PIDS=""; local gem5_arr=()
    for nid in $(seq 0 $((NUM_NODES-1))); do
        local gdir="$LOG_BASE/gem5_tc${tc}_node${nid}"
        local node_od="$m5outdir/node${nid}"
        mkdir -p "$gdir" "$node_od"
        local cmd
        cmd="$(expand_cmd gem5_${nid} '' "$node_od")"
        echo "[launch] gem5 node=$nid (outdir=$node_od)"
        eval "$cmd" 2>"$gdir/stderr.log" >"$gdir/stdout.log" &
        local pid=$!
        gem5_arr+=($pid)
        GEM5_PIDS="$GEM5_PIDS $pid"
    done

    # Wait for STEP5 Port enabled (NUM_SOCKETS of them per node)
    echo "[launch] waiting for NUM_NODES=$NUM_NODES gem5 to bind (sockets=$NUM_SOCKETS)..."
    for nid in $(seq 0 $((NUM_NODES-1))); do
        local gout="$LOG_BASE/gem5_tc${tc}_node${nid}/stdout.log"
        local bound=0
        for tries in $(seq 1 90); do
            if [ "$(grep -c 'STEP5.*Port enabled' "$gout" 2>/dev/null)" -ge "$NUM_SOCKETS" ]; then
                bound=1; break
            fi
            if ! kill -0 ${gem5_arr[$nid]} 2>/dev/null; then
                echo "[launch] gem5 node=$nid exited before binding!"
                return 1
            fi
            sleep 1
        done
        [ $bound -eq 1 ] && echo "[launch]   node=$nid bound" || { echo "[launch] node=$nid bind TIMEOUT"; return 1; }
    done

    # 5. Start N*K ubio processes (plane = node*K + socket)
    UBIO_PIDS=""
    local frules; frules="$(fault_rules_for_tc "$tc")"
    local frargs=""
    [ -n "$frules" ] && frargs="--fault-rules=$frules"
    [ -n "$frules" ] && echo "[launch] fault rules (TC${tc}): $frules"
    for nid in $(seq 0 $((NUM_NODES-1))); do
        for sid in $(seq 0 $((NUM_SOCKETS-1))); do
            local mod_id="ubio_${nid}_s${sid}"
            # In 1s the JSON uses ubio_<nid> (no _s0 suffix); fall back.
            local cmd
            if python3 -c "import json,sys;sys.exit(0 if any(m['id']==sys.argv[1] for m in json.load(open('$JSON'))['modules']) else 1)" "$mod_id" 2>/dev/null; then
                cmd="$(expand_cmd "$mod_id" "$frargs")"
            else
                cmd="$(expand_cmd "ubio_${nid}" "$frargs")"
            fi
            local logdir="$LOG_BASE/ubio_n${nid}_s${sid}"
            mkdir -p "$logdir"
            eval "$cmd" 2>"$logdir/stderr.log" >"$logdir/stdout.log" &
            UBIO_PIDS="$UBIO_PIDS $!"
        done
    done
    local n_ubio; n_ubio=$(echo $UBIO_PIDS | wc -w)
    echo "[launch] $n_ubio ubio (${NUM_NODES}x${NUM_SOCKETS}) + $NUM_NODES gem5 running"

    # 6. Wait for all gem5 processes to finish (or timeout)
    local waited=0
    while true; do
        local any=0
        for pid in $GEM5_PIDS; do
            if kill -0 $pid 2>/dev/null; then any=1; fi
        done
        [ $any -eq 0 ] && break
        sleep 1; waited=$((waited + 1))
        if [ $waited -ge "$TIMEOUT_SEC" ]; then
            echo "  TC${tc} TIMEOUT after ${TIMEOUT_SEC}s"
            for pid in $GEM5_PIDS; do kill $pid 2>/dev/null || true; done
            return 1
        fi
    done

    # Check exit codes
    local gem5_fail=0
    for pid in $GEM5_PIDS; do
        wait $pid 2>/dev/null || gem5_fail=1
    done

    # Kill ubio/nsim
    for pid in $UBIO_PIDS; do kill -9 $pid 2>/dev/null || true; done
    kill -9 ${NSIM_PID:-} 2>/dev/null || true
    wait 2>/dev/null || true
    sleep 0.2

    if [ $gem5_fail -ne 0 ]; then
        echo "  TC${tc} CRASHED (a gem5 node exited non-zero)"
        return 1
    fi

    # 7. Verify via independent verify.py
    local simouts=()
    for nid in $(seq 0 $((NUM_NODES-1))); do
        simouts+=("$m5outdir/node${nid}/simout_n${nid}")
    done
    local faultlogs=()
    for nid in $(seq 0 $((NUM_NODES-1))); do
        for sid in $(seq 0 $((NUM_SOCKETS-1))); do
            faultlogs+=("$LOG_BASE/ubio_n${nid}_s${sid}/stderr.log")
        done
    done
    local vlog="$LOG_BASE/verify_tc${tc}.log"
    python3 "$ROOT_DIR/tests/e2e/verify.py" --tc=$tc \
        --simout "${simouts[@]}" --fault-log "${faultlogs[@]}" 2>&1 | tee "$vlog"
    # Last sentinel line decides
    if tail -n1 "$vlog" 2>/dev/null | grep -q ">>> TC${tc} PASSED <<<"; then
        echo "  TC${tc} PASSED"
        return 0
    else
        echo "  TC${tc} FAILED"
        return 1
    fi
}

# ── Main ─────────────────────────────────────────────────────────────
[ -x "$GEM5_BIN" ] || { echo "FATAL: $GEM5_BIN not built"; exit 2; }
[ -x "$UBIO_BIN" ] || [ -x "$NSIM_BIN" ] || { echo "FATAL: native binaries not built"; exit 2; }

echo "=== Multi-Process E2E Runner (decoupled, topo=$TOPO_KIND) ==="
echo "Config:  $JSON"
echo "Log base: $LOG_BASE"
echo "Sockets/node: $NUM_SOCKETS  (NMOD=$NMOD)"
echo "Workload: $WORKLOAD  (compiled per-TC; path is constant)"

# Sanity: warn if a --2s-only TC is passed under 1s
if [ "$TOPO_KIND" = "1s" ]; then
    for tc in "$@"; do
        case "$tc" in 32|33|34|35|39)
            echo "FATAL: TC$tc requires --2s topology. Re-run with --2s." >&2
            exit 2
        ;; esac
    done
fi

PASS=0; FAIL=0
for tc in "$@"; do
    if UBIO_PIDS="" run_tc "$tc"; then PASS=$((PASS+1)); else FAIL=$((FAIL+1)); fi
    # cleanup any stragglers between TCs
    for pid in ${UBIO_PIDS:-} ${NSIM_PID:-}; do kill $pid 2>/dev/null || true; done
done

echo ""
echo "=== Results: $PASS pass, $FAIL fail ==="
echo "Logs: $LOG_BASE"