#!/bin/bash
# Multi-Process E2E Runner (per-node gem5 split) — decoupled edition
#
# This launcher reads a fixed JSON topology config (configs/topo_1s.json or
# configs/topo_2s.json), generates the networksim topo.json, compiles the
# workload into a run-specific path, starts all module processes per the JSON,
# waits for gem5 to finish, then invokes the independent verifier
# tests/e2e/verify.py. Set E2E_RUN_ID to run independent TCs concurrently.
#
# Usage:
#   bash tests/e2e/run_multi.sh [--1s|--2s] <tc> ... [<tc> ...]
#
# Default is --1s. Dual-socket TCs (32-35,39) require --2s; if you pass a
# dual-socket TC under --1s the script will auto-error.
#
# topology (*) is fixed in the JSON files; the networksim crossbar mesh is
# regenerated by scripts/gen_topo.py to match (NMOD depends only on topology).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
GEM5_BIN="$ROOT_DIR/gem5/build/ARM/gem5.opt"
UBIO_BIN="$ROOT_DIR/build/bin/ubio"
NSIM_BIN="$ROOT_DIR/build/bin/networksim"
TEST_E2E="$ROOT_DIR/tests/e2e/test_e2e.py"
RUN_ID="${E2E_RUN_ID:-$(date +%Y%m%d_%H%M%S)_$$}"
RUN_DIR="$ROOT_DIR/build/runs/$RUN_ID"
WORKLOAD="$RUN_DIR/workload.elf"
TOPO_JSON="$RUN_DIR/topo.json"
IPC_DIR="$RUN_DIR/ipc"
TIMEOUT_SEC="${TIMEOUT_SEC:-600}"

# C5: PDES sync interval (ps).  Lower values improve time-resolution but
# increase IPC overhead.  Target: 2.5ns (2500 ps) per solve_latency_params.py --x-ns 2.5.
export EP_SYNC_INTERVAL_PS="${EP_SYNC_INTERVAL_PS:-2500}"
export EP_LINK_LATENCY_PS="${EP_LINK_LATENCY_PS:-2500}"

# ── Config selection ────────────────────────────────────────────────
TOPO_KIND="1s"
case "${1:-}" in
    --1s)          TOPO_KIND="1s"; shift ;;
    --1s-tinydir)  TOPO_KIND="1s_tinydir"; shift ;;
    --2s)          TOPO_KIND="2s"; shift ;;
    --8n1s)        TOPO_KIND="8n1s"; shift ;;
    --8n2s)        TOPO_KIND="8n2s"; shift ;;
esac
JSON="$ROOT_DIR/configs/topo_${TOPO_KIND}.json"
[ -f "$JSON" ] || { echo "FATAL: config $JSON not found" >&2; exit 2; }

# ── Determine sockets + nmod from JSON ───────────────────────────────
read NUM_NODES NUM_SOCKETS < <(python3 -c "
import json
c=json.load(open('$JSON'))
print(c['num_nodes'], c['num_sockets'])
")
NMOD=$((NUM_NODES * NUM_SOCKETS))

# ── Per-TC fault-injection rules (ubio --fault-rules=...) ────────────
fault_rules_for_tc() {
    case "$1" in
        47) echo "tc47_dup_clear:ClearReq:1:0:0:dup::1" ;;
        48) echo "tc48_dup_inv_ack:InvalidateAck:2:0:0:dup::1" ;;
        49) echo "tc49_dup_inv_ack:InvalidateAck:1:0:0:dup::1" ;;
        110) echo "tc110_drop_clear:ClearReq:1:1:0:drop::1" ;;
        111) echo "tc111_silent_upgrade_drop:UpgradeReq:1:1:0:drop::1" ;;
        117) echo "tc117_reorder_clear:ClearReq:0:1:0:reorder:100000:1" ;;
        118) echo "tc118_drop:ClearReq:0:1:0x10018011800:drop::1;tc118_delay:ClearReq:0:1:0x10018011900:delay:100000:1" ;;
        119) echo "tc119_drop:ClearReq:0:1:0x10018011900:drop::1;tc119_dup:ClearReq:0:1:0x10018011940:dup::1;tc119_delay:ClearReq:0:1:0x10018011980:delay:100000:1" ;;
        *)  echo "" ;;
    esac
}

# ── Per-TC extra ubio args (ResidentDir params, etc.) ──────────────
ubio_extra_args_for_tc() {
    case "$1" in
        116) echo "--bloom-bytes=512 --sram-bytes=6144 --ways=2 ${UBCC_POLICY:+--dir-overflow-policy=$UBCC_POLICY} ${UBCC_OPTS:-}" ;;
        120)
            case "${EP_PERF_PROFILE:-optimized}" in
                baseline) echo "--bloom-bytes=512 --sram-bytes=5000 --ways=2 --set-bits=2 --dir-overflow-policy=${UBCC_POLICY:-naive} --batch-rs=0 ${UBCC_OPTS:-}" ;;
                optimized|*) echo "--bloom-bytes=512 --sram-bytes=5000 --ways=2 --set-bits=2 --dir-overflow-policy=${UBCC_POLICY:-spill} --batch-rs=1 ${UBCC_OPTS:-}" ;;
            esac
            ;;
        121)
            case "${EP_PERF_PROFILE:-optimized}" in
                baseline) echo "--bloom-bytes=512 --sram-bytes=5000 --ways=2 --set-bits=2 --dir-overflow-policy=${UBCC_POLICY:-naive} --batch-rs=0 ${UBCC_OPTS:-}" ;;
                optimized|*) echo "--bloom-bytes=512 --sram-bytes=5000 --ways=2 --set-bits=2 --dir-overflow-policy=${UBCC_POLICY:-spill} --batch-rs=1 ${UBCC_OPTS:-}" ;;
            esac
            ;;
        122|123)
            case "${EP_PERF_PROFILE:-optimized}" in
                baseline) echo "--bloom-bytes=512 --sram-bytes=6144 --ways=2 --dir-overflow-policy=${UBCC_POLICY:-naive} --batch-rs=0 ${UBCC_OPTS:-}" ;;
                optimized|*) echo "--bloom-bytes=512 --sram-bytes=6144 --ways=2 --dir-overflow-policy=${UBCC_POLICY:-spill} --batch-rs=1 ${UBCC_OPTS:-}" ;;
            esac
            ;;
        124)
            case "${EP_PERF_PROFILE:-optimized}" in
                baseline) echo "--batch-rs=0 ${UBCC_OPTS:-}" ;;
                optimized|*) echo "--batch-rs=1 ${UBCC_OPTS:-}" ;;
            esac
            ;;
        126)
            echo "--bloom-bytes=512 --sram-bytes=6144 --ways=1 --dir-overflow-policy=spill --batch-rs=0 ${UBCC_OPTS:-}"
            ;;
        125|127|128|129)
            echo "--bloom-bytes=512 --sram-bytes=6144 --ways=1 --dir-overflow-policy=spill --batch-rs=0 ${UBCC_OPTS:-}"
            ;;
        130)
            echo "--bloom-bytes=${UBCC_BLOOM_BYTES:-512} --sram-bytes=5000 --ways=2 --set-bits=2 --dir-overflow-policy=${UBCC_POLICY:-spill} --batch-rs=0 ${UBCC_OPTS:-}"
            ;;
        131|132|133|134)
            local bloom_bytes=61440
            if [ "${UBCC_POLICY:-spill}" = "naive" ]; then
                bloom_bytes=0
            fi
            echo "--bloom-bytes=$bloom_bytes --sram-bytes=524288 --ways=0 --set-bits=0 --dir-overflow-policy=${UBCC_POLICY:-spill} --batch-rs=0 ${UBCC_OPTS:-}"
            ;;
        98)  echo "--ways=1" ;;
        *)   echo "" ;;
    esac
}

# ─── Lookup json module command (placeholder substitution) ────────────
# expand_cmd <module_id> <fault_rules> <ubio_extra_args> [node_outdir]
# Env: runtime paths used to substitute runner-specific placeholders.
expand_cmd() {
    local mod_id="$1"; local frules="$2"; local uextra="$3"; local node_od="${4:-}"
    NODE_OUTDIR="$node_od" python3 - "$JSON" "$mod_id" "$frules" "$uextra" <<'PY'
import json, os, sys
cfg_path, mod_id, frules, uextra = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4]
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(cfg_path)))
c = json.load(open(cfg_path))
mod = next((m for m in c["modules"] if m["id"]==mod_id), None)
if not mod:
    sys.exit(2)
def r(s):
    s = s.replace("{root}", ROOT)
    s = s.replace("{gem5_bin}", os.path.join(ROOT,"gem5/build/ARM/gem5.opt"))
    s = s.replace("{ubio_bin}", os.path.join(ROOT,"build/bin/ubio"))
    s = s.replace("{nsim_bin}", os.path.join(ROOT,"build/bin/networksim"))
    s = s.replace("{test_e2e}", os.path.join(ROOT,"tests/e2e/test_e2e.py"))
    s = s.replace("{workload}", os.environ["RUN_WORKLOAD"])
    s = s.replace("{topo_json}", os.environ["RUN_TOPO_JSON"])
    s = s.replace("{node_outdir}", os.environ.get("NODE_OUTDIR",""))
    s = s.replace("{fault_rules_args}", frules)
    s = s.replace("{ubio_extra_args}", uextra)
    return s
print(r(mod["cmd"]))
PY
}

# ─── per-TC run ─────────────────────────────────────────────────────
LOG_BASE="${LOG_BASE:-$ROOT_DIR/logs/$(date +%Y%m%d_%H%M%S)_${TOPO_KIND}}"
mkdir -p "$LOG_BASE" "$RUN_DIR" "$IPC_DIR"
export UBCC_IPC_DIR="$IPC_DIR"
export RUN_WORKLOAD="$WORKLOAD"
export RUN_TOPO_JSON="$TOPO_JSON"

# Kill any leftover infra from a previous TC / abort.
_kill_infra() {
    for pid in ${UBIO_PIDS:-} ${NSIM_PID:-}; do
        kill -9 $pid 2>/dev/null || true
    done
    if [ -n "${MEMORY_MONITOR_PID:-}" ]; then
        kill "$MEMORY_MONITOR_PID" 2>/dev/null || true
        MEMORY_MONITOR_PID=""
    fi
    wait 2>/dev/null || true
    sleep 0.3
    UBIO_PIDS=""; NSIM_PID=""
}
_record_runner_signal() {
    local signal=$1
    printf '[runner] signal=%s pid=%s tc=%s\n' "$signal" "$$" "${CURRENT_TC:-none}" \
        >>"${LOG_BASE:-/tmp}/runner_signals.log"
}
trap '_record_runner_signal EXIT; _kill_infra' EXIT
trap '_record_runner_signal HUP; exit 129' HUP
trap '_record_runner_signal INT; exit 130' INT
trap '_record_runner_signal TERM; exit 143' TERM

_start_memory_monitor() {
    local tc=$1
    local interval="${E2E_MEMORY_MONITOR_SEC:-0}"
    [ "$interval" -gt 0 ] 2>/dev/null || return

    local log="$LOG_BASE/memory_tc${tc}.log"
    (
        while true; do
            date '+[MEMORY] %FT%T%z'
            free -b
            ps -eo pid=,ppid=,rss=,vsz=,comm= | \
                while read -r pid ppid rss vsz comm; do
                    case "$comm" in
                        gem5.opt|ubio|networksim)
                            printf '[MEMORY-PROC] pid=%s ppid=%s rss_kb=%s vsz_kb=%s cmd=%s\n' \
                                "$pid" "$ppid" "$rss" "$vsz" "$comm"
                            ;;
                    esac
                done
            sleep "$interval"
        done
    ) >>"$log" 2>&1 &
    MEMORY_MONITOR_PID=$!
    echo "[monitor] memory sampling every ${interval}s -> $log"
}

run_tc() {
    local tc=$1
    CURRENT_TC=$tc
    _kill_infra  # ensure clean state before each TC

    # TC98 fix: per-TC timeout override.  High-contention tests need much
    # longer than the default 600s because PDES serialization is inherent.
    local TC_TIMEOUT="$TIMEOUT_SEC"
    case "$tc" in
        98) TC_TIMEOUT="${TIMEOUT_SEC_TC98:-1500}" ;;  # floor 1500s, overridable
        128) TC_TIMEOUT="${TIMEOUT_SEC_TC128:-1800}" ;; # full cache sweep + onload
        131) TC_TIMEOUT="${TIMEOUT_SEC_TC131:-7200}" ;;
        132) TC_TIMEOUT="${TIMEOUT_SEC_TC132:-7200}" ;;
        133) TC_TIMEOUT="${TIMEOUT_SEC_TC133:-7200}" ;;
        134) TC_TIMEOUT="${TIMEOUT_SEC_TC134:-7200}" ;;
    esac
    # Always respect a higher value passed via TIMEOUT_SEC env var
    if [ "$TIMEOUT_SEC" -gt "$TC_TIMEOUT" ] 2>/dev/null; then
        TC_TIMEOUT="$TIMEOUT_SEC"
    fi

    local m5base="$RUN_DIR/tc${tc}"
    local m5outdir="$m5base/m5out"
    rm -rf "$m5base"; mkdir -p "$m5outdir"

    echo ""
    echo "=== TC${tc} (topo=$TOPO_KIND, ${NUM_NODES}nodes x ${NUM_SOCKETS}sockets) ==="

    # 1. Compile workload into this run's private ELF path.
    NUM_NODES="$NUM_NODES" NUM_SOCKETS="$NUM_SOCKETS" \
        WORKLOAD_OUT="$WORKLOAD" bash "$ROOT_DIR/scripts/compile_workload.sh" "$tc" >/dev/null 2>&1 \
        || { echo "  TC${tc} COMPILE FAILED"; return 1; }

    # 2. Generate networksim topo.json (full mesh, --nodes/--sockets from JSON)
    python3 "$ROOT_DIR/scripts/gen_topo.py" --nodes "$NUM_NODES" --sockets "$NUM_SOCKETS" --out "$TOPO_JSON" >/dev/null 2>&1
    # Clean only this run's IPC endpoints. Other runs use distinct directories.
    rm -rf "$IPC_DIR" 2>/dev/null || true
    mkdir -p "$IPC_DIR"

    # 3. Start networksim (must bind before ubio connects)
    local nsim_cmd
    nsim_cmd="$(expand_cmd networksim '' '')"
    echo "[launch] networksim (NMOD=$NMOD)"
    eval "$nsim_cmd" >"$LOG_BASE/nsim_tc${tc}.log" 2>&1 &
    NSIM_PID=$!
    sleep 1

    # 4. Start N gem5 nodes, wait until each binds its ports (STEP5 marker)
    GEM5_PIDS=""; local gem5_arr=()
    for nid in $(seq 0 $((NUM_NODES-1))); do
        local gdir="$LOG_BASE/gem5_tc${tc}_node${nid}"
        local node_od="$m5outdir/node${nid}"
        mkdir -p "$gdir" "$node_od"
        local cmd
        cmd="$(expand_cmd gem5_${nid} '' '' "$node_od")"
        # Optional per-node gem5 tracing for long-running E2E diagnosis.
        # Keep the debug stream separate from stderr so runner diagnostics stay usable.
        if [ -n "${GEM5_DEBUG_FLAGS:-}" ]; then
            local debug_args="--debug-flags=${GEM5_DEBUG_FLAGS} --debug-file=$gdir/gem5_debug.log"
            if [ -n "${GEM5_DEBUG_START:-}" ]; then
                debug_args="$debug_args --debug-start=${GEM5_DEBUG_START}"
            fi
            cmd="$GEM5_BIN $debug_args${cmd#"$GEM5_BIN"}"
        fi
        if [ "$tc" = "130" ] || [ "$tc" = "132" ] || [ "$tc" = "133" ] || [ "$tc" = "134" ]; then
            # These tests isolate directory policy; do not mix protocol optimizations.
            cmd="$cmd --silent-upgrade=0 --direct-fwd=0 --ubcc-batch-rs=0"
        elif [ "$tc" = "131" ]; then
            # TC131 is the capacity/latency comparison workload.  The baseline
            # is naive with every latency optimization disabled; optimized uses
            # spill and enables the latency optimization profile.
            case "${EP_PERF_PROFILE:-baseline}" in
                optimized) cmd="$cmd --silent-upgrade=1 --direct-fwd=0 --ubcc-batch-rs=1" ;;
                *)         cmd="$cmd --silent-upgrade=0 --direct-fwd=0 --ubcc-batch-rs=0" ;;
            esac
        elif [ "$tc" = "120" ] || [ "$tc" = "121" ] || [ "$tc" = "122" ] || [ "$tc" = "123" ] || [ "$tc" = "124" ]; then
            case "${EP_PERF_PROFILE:-optimized}" in
                baseline)
                    cmd="$cmd --silent-upgrade=0 --direct-fwd=0 --ubcc-batch-rs=0"
                    ;;
                optimized|*)
                    cmd="$cmd --silent-upgrade=1 --direct-fwd=0 --ubcc-batch-rs=1"
                    ;;
            esac
        fi
        echo "[launch] gem5 node=$nid (outdir=$node_od)"
        eval "$cmd" 2>"$gdir/stderr.log" >"$gdir/stdout.log" &
        local pid=$!
        gem5_arr+=($pid)
        GEM5_PIDS="$GEM5_PIDS $pid"
    done

    # Wait for STEP5 Port enabled (NUM_SOCKETS of them per node)
    echo "[launch] waiting for NUM_NODES=$NUM_NODES gem5 to bind (sockets=$NUM_SOCKETS)..."
    for nid in $(seq 0 $((NUM_NODES-1))); do
        local gout="$LOG_BASE/gem5_tc${tc}_node${nid}/stdout.log"
        local bound=0
        for tries in $(seq 1 300); do    # up to 300s wait (8-node init takes time)
            if [ "$(grep -c 'STEP5.*Port enabled' "$gout" 2>/dev/null)" -ge "$NUM_SOCKETS" ]; then
                bound=1; break
            fi
            if ! kill -0 ${gem5_arr[$nid]} 2>/dev/null; then
                echo "[launch] gem5 node=$nid exited before binding!"
                return 1
            fi
            sleep 1
        done
        [ $bound -eq 1 ] && echo "[launch]   node=$nid bound" || { echo "[launch] node=$nid bind TIMEOUT"; return 1; }
    done

    # 5. Start N*K ubio processes (plane = node*K + socket)
    UBIO_PIDS=""
    local frules; frules="$(fault_rules_for_tc "$tc")"
    local frargs=""
    [ -n "$frules" ] && frargs="--fault-rules=$frules"
    [ -n "$frules" ] && echo "[launch] fault rules (TC${tc}): $frules"
    local uextra; uextra="$(ubio_extra_args_for_tc "$tc")"
    [ -n "$uextra" ] && echo "[launch] ubio extra args (TC${tc}): $uextra"
    for nid in $(seq 0 $((NUM_NODES-1))); do
        for sid in $(seq 0 $((NUM_SOCKETS-1))); do
            local mod_id="ubio_${nid}_s${sid}"
            local cmd
            if python3 -c "import json,sys;sys.exit(0 if any(m['id']==sys.argv[1] for m in json.load(open('$JSON'))['modules']) else 1)" "$mod_id" 2>/dev/null; then
                cmd="$(expand_cmd "$mod_id" "$frargs" "$uextra")"
            else
                cmd="$(expand_cmd "ubio_${nid}" "$frargs" "$uextra")"
            fi
            local logdir="$LOG_BASE/ubio_n${nid}_s${sid}"
            mkdir -p "$logdir"
            eval "$cmd" 2>"$logdir/stderr.log" >"$logdir/stdout.log" &
            UBIO_PIDS="$UBIO_PIDS $!"
        done
    done
    local n_ubio; n_ubio=$(echo $UBIO_PIDS | wc -w)
    echo "[launch] $n_ubio ubio (${NUM_NODES}x${NUM_SOCKETS}) + $NUM_NODES gem5 running"
    _start_memory_monitor "$tc"

    # 6. Wait for all gem5 processes to finish (or timeout)
    local waited=0
    local progress_file="$m5outdir/node0/simout_n0"
    local progress_size=-1
    local progress_waited=0
    local progress_watchdog="${PROGRESS_WATCHDOG_SEC:-0}"
    while true; do
        local any=0
        for pid in $GEM5_PIDS; do
            # A completed child remains a zombie until the wait below reaps it.
            # kill -0 succeeds for zombies, so do not mistake one for a running
            # gem5 process and leave UBIO/networksim running indefinitely.
            if kill -0 "$pid" 2>/dev/null; then
                local state
                state=$(ps -o stat= -p "$pid" 2>/dev/null || true)
                state=${state#${state%%[![:space:]]*}}
                case "$state" in
                    Z*) ;;
                    *) any=1 ;;
                esac
            fi
        done
        [ $any -eq 0 ] && break
        sleep 1; waited=$((waited + 1))
        if [ "$progress_watchdog" -gt 0 ] 2>/dev/null; then
            local current_size=0
            [ -f "$progress_file" ] && current_size=$(stat -c %s "$progress_file")
            if [ "$current_size" -ne "$progress_size" ]; then
                progress_size="$current_size"
                progress_waited=0
            else
                progress_waited=$((progress_waited + 1))
                if [ "$progress_waited" -ge "$progress_watchdog" ]; then
                    echo "  TC${tc} PROGRESS STALL after ${progress_watchdog}s (no node0 guest output)"
                    for pid in $GEM5_PIDS; do kill $pid 2>/dev/null || true; done
                    return 1
                fi
            fi
        fi
        if [ $waited -ge "$TC_TIMEOUT" ]; then
            # TC9 is a negative test: node0 is expected to crash on non-DSM
            # access (Aborted/SIGSEGV). If that crash evidence exists, the
            # test PASSED despite the timeout (other nodes may keep spinning).
            if [ "$tc" -eq 9 ]; then
                local crash_log="$LOG_BASE/gem5_tc${tc}_node0/stderr.log"
                if grep -qE "Aborted|core dumped|SIGSEGV" "$crash_log" 2>/dev/null; then
                    echo "  TC${tc} PASSED (expected crash detected)"
                    for pid in $GEM5_PIDS; do kill $pid 2>/dev/null || true; done
                    return 0
                fi
                echo "  TC${tc} TIMEOUT (no crash evidence found)"
            else
                echo "  TC${tc} TIMEOUT after ${TC_TIMEOUT}s"
            fi
            for pid in $GEM5_PIDS; do kill $pid 2>/dev/null || true; done
            return 1
        fi
    done

    # Check exit codes
    local gem5_fail=0
    for pid in $GEM5_PIDS; do
        wait $pid 2>/dev/null || gem5_fail=1
    done

    # Kill ubio/nsim
    for pid in $UBIO_PIDS; do kill -9 $pid 2>/dev/null || true; done
    kill -9 ${NSIM_PID:-} 2>/dev/null || true
    if [ -n "${MEMORY_MONITOR_PID:-}" ]; then
        kill "$MEMORY_MONITOR_PID" 2>/dev/null || true
        MEMORY_MONITOR_PID=""
    fi
    wait 2>/dev/null || true
    sleep 0.2

    if [ $gem5_fail -ne 0 ]; then
        echo "  TC${tc} CRASHED (a gem5 node exited non-zero)"
        return 1
    fi

    # 7. Verify via independent verify.py
    local simouts=()
    for nid in $(seq 0 $((NUM_NODES-1))); do
        local simout="$m5outdir/node${nid}/simout_n${nid}"
        simouts+=("$simout")
        if [ -f "$simout" ]; then
            cp "$simout" "$LOG_BASE/simout_tc${tc}_node${nid}.log" 2>/dev/null || true
        fi
    done
    local faultlogs=()
    for nid in $(seq 0 $((NUM_NODES-1))); do
        for sid in $(seq 0 $((NUM_SOCKETS-1))); do
            faultlogs+=("$LOG_BASE/ubio_n${nid}_s${sid}/stderr.log")
            faultlogs+=("$LOG_BASE/ubio_n${nid}_s${sid}/stdout.log")
        done
    done
    local vlog="$LOG_BASE/verify_tc${tc}.log"
    python3 "$ROOT_DIR/tests/e2e/verify.py" --tc=$tc \
        --simout "${simouts[@]}" --fault-log "${faultlogs[@]}" 2>&1 | tee "$vlog"
    # Last sentinel line decides
    if tail -n1 "$vlog" 2>/dev/null | grep -q ">>> TC${tc} PASSED <<<"; then
        # Persist request issue-to-first-response chains for cross-run latency
        # evaluation.  TRACE-PERF is emitted by gem5, UBIO, and networksim.
        python3 "$ROOT_DIR/scripts/trace2chain.py" "$LOG_BASE" \
            >"$LOG_BASE/trace_chains_tc${tc}.json" 2>/dev/null || true
        echo "  TC${tc} PASSED"
        return 0
    else
        echo "  TC${tc} FAILED"
        return 1
    fi
}

# ── Main ─────────────────────────────────────────────────────────────
[ -x "$GEM5_BIN" ] || { echo "FATAL: $GEM5_BIN not built"; exit 2; }
[ -x "$UBIO_BIN" ] || [ -x "$NSIM_BIN" ] || { echo "FATAL: native binaries not built"; exit 2; }

echo "=== Multi-Process E2E Runner (decoupled, topo=$TOPO_KIND) ==="
echo "Config:  $JSON"
echo "Log base: $LOG_BASE"
echo "Sockets/node: $NUM_SOCKETS  (NMOD=$NMOD)"
echo "Workload: $WORKLOAD  (compiled per-TC; path is constant)"

# Sanity: warn if a --2s-only TC is passed under 1s
if [ "$TOPO_KIND" = "1s" ]; then
    for tc in "$@"; do
        case "$tc" in 32|33|34|35|39|81)
            echo "FATAL: TC$tc requires --2s topology. Re-run with --2s." >&2
            exit 2
        ;; esac
    done
fi

# Sanity: warn if an 8n2s-only TC is passed under 8n1s (or non-8n2s)
if [ "$TOPO_KIND" = "8n1s" ]; then
    for tc in "$@"; do
        case "$tc" in 95|96|97|98|99|134)
            echo "FATAL: TC$tc requires --8n2s topology. Re-run with --8n2s." >&2
            exit 2
        ;; esac
    done
fi

PASS=0; FAIL=0
for tc in "$@"; do
    if UBIO_PIDS="" run_tc "$tc"; then PASS=$((PASS+1)); else FAIL=$((FAIL+1)); fi
    # cleanup any stragglers between TCs
    for pid in ${UBIO_PIDS:-} ${NSIM_PID:-}; do kill $pid 2>/dev/null || true; done
done

echo ""
echo "=== Results: $PASS pass, $FAIL fail ==="
echo "Logs: $LOG_BASE"
