#!/bin/bash
# Multi-Process E2E Runner (per-node gem5 split) — decoupled edition
#
# This launcher reads a fixed JSON topology config (configs/topo_1s.json or
# configs/topo_2s.json), generates the networksim topo.json, compiles the
# workload into a run-specific path, starts all module processes per the JSON,
# waits for gem5 to finish, then invokes the independent verifier
# tests/e2e/verify.py. Set E2E_RUN_ID to run independent TCs concurrently.
#
# Usage:
#   bash tests/e2e/run_multi.sh [--1s|--2s] <tc> ... [<tc> ...]
#
# Default is --1s. Dual-socket TCs (32-35,39) require --2s; if you pass a
# dual-socket TC under --1s the script will auto-error.
#
# ── Long-run supervised invocation ────────────────────────────────────
# The runner does NOT background itself. For long-running TCs (132-134):
#   nohup env EP_SUPERVISOR=1 bash tests/e2e/run_multi.sh --8n1s 132 \
#     > /tmp/run_132.log 2>&1 &
# Opt-in supervisor (EP_SUPERVISOR=1) adds watchdog monitoring with:
#   - PID manifest in LOG_BASE
#   - Periodic liveness / progress / log-size / disk-free checks
#   - Clean per-TC kill on fault; never uses pkill
# Supervisor env vars (all default-off):
#   EP_SUPERVISOR=1              enable (default unset=off)
#   EP_SUPERVISOR_INTERVAL=30    check interval seconds (default 30)
#   EP_SUPERVISOR_LOG_CEIL_GB=20 max log dir GiB ceiling (default 20)
#   EP_SUPERVISOR_DISK_FREE_GB=50 min disk free GiB (default 50)
#   EP_SUPERVISOR_PROGRESS_STALL_SEC=600 stop after no simout growth
#
# TRACE-PERF is bounded by default to prevent capacity tests from producing
# one record per protocol hop. The first 500 events per process are retained.
#   EP_TRACE_PERF=sample|full|off  (default sample)
#   EP_TRACE_PERF_FIRST_N=500 EP_TRACE_PERF_MAX=2000 EP_TRACE_PERF_EVERY=0
# Full mode preserves the historical every-event trace; add MAX explicitly
# when a diagnostic run must also have a finite output budget.
# IPC is bounded by default so a stalled peer exerts backpressure rather than
# consuming host memory. Override only for controlled transport experiments.
#   EP_PORT_HWM=8192 EP_NSIM_MAX_PENDING=65536
#
# topology (*) is fixed in the JSON files; the networksim crossbar mesh is
# regenerated by scripts/gen_topo.py to match (NMOD depends only on topology).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
GEM5_BIN="$ROOT_DIR/gem5/build/ARM/gem5.opt"
UBIO_BIN="$ROOT_DIR/build/bin/ubio"
NSIM_BIN="$ROOT_DIR/build/bin/networksim"
TEST_E2E="$ROOT_DIR/tests/e2e/test_e2e.py"
RUN_ID="${E2E_RUN_ID:-$(date +%Y%m%d_%H%M%S)_$$}"
RUN_DIR="$ROOT_DIR/build/runs/$RUN_ID"
WORKLOAD="$RUN_DIR/workload.elf"
TOPO_JSON="$RUN_DIR/topo.json"
IPC_DIR="$RUN_DIR/ipc"
TIMEOUT_SEC="${TIMEOUT_SEC:-600}"

# ── Supervisor (opt-in long-run watchdog) conf ─────────────────────
EP_SUPERVISOR="${EP_SUPERVISOR:-0}"
EP_SUPERVISOR_INTERVAL="${EP_SUPERVISOR_INTERVAL:-30}"
EP_SUPERVISOR_LOG_CEIL_GB="${EP_SUPERVISOR_LOG_CEIL_GB:-20}"
EP_SUPERVISOR_DISK_FREE_GB="${EP_SUPERVISOR_DISK_FREE_GB:-50}"
EP_SUPERVISOR_PROGRESS_STALL_SEC="${EP_SUPERVISOR_PROGRESS_STALL_SEC:-600}"

# C5: PDES sync interval (ps).  Lower values improve time-resolution but
# increase IPC overhead.  Target: 2.5ns (2500 ps) per solve_latency_params.py --x-ns 2.5.
export EP_SYNC_INTERVAL_PS="${EP_SYNC_INTERVAL_PS:-2500}"
export EP_LINK_LATENCY_PS="${EP_LINK_LATENCY_PS:-2500}"

# Phase 0: Metadata DRAM capacity — single source of truth for gem5 and ubio.
# gem5 gets --ubcc_metadata_size; ubio gets --metadata-dram-bytes.
# Both default to 128 MiB (134217728 bytes).  Override this variable to
# use a different capacity (e.g. 16 MiB legacy: UBCC_METADATA_SIZE=16777216).
export UBCC_METADATA_SIZE="${UBCC_METADATA_SIZE:-134217728}"
export EP_TRACE_PERF="${EP_TRACE_PERF:-sample}"
export EP_TRACE_PERF_FIRST_N="${EP_TRACE_PERF_FIRST_N:-500}"
export EP_TRACE_PERF_MAX="${EP_TRACE_PERF_MAX:-2000}"
export EP_TRACE_PERF_EVERY="${EP_TRACE_PERF_EVERY:-0}"
export EP_PORT_HWM="${EP_PORT_HWM:-8192}"
export EP_NSIM_MAX_PENDING="${EP_NSIM_MAX_PENDING:-65536}"

# ── Config selection ────────────────────────────────────────────────
TOPO_KIND="1s"
case "${1:-}" in
    --1s)          TOPO_KIND="1s"; shift ;;
    --1s-tinydir)  TOPO_KIND="1s_tinydir"; shift ;;
    --2s)          TOPO_KIND="2s"; shift ;;
    --8n1s)        TOPO_KIND="8n1s"; shift ;;
    --8n2s)        TOPO_KIND="8n2s"; shift ;;
    --2n1s)        TOPO_KIND="2n1s"; shift ;;
esac
JSON="$ROOT_DIR/configs/topo_${TOPO_KIND}.json"
[ -f "$JSON" ] || { echo "FATAL: config $JSON not found" >&2; exit 2; }

# ── Determine sockets + nmod from JSON ───────────────────────────────
read NUM_NODES NUM_SOCKETS < <(python3 -c "
import json
c=json.load(open('$JSON'))
print(c['num_nodes'], c['num_sockets'])
")
NMOD=$((NUM_NODES * NUM_SOCKETS))

# ── Per-TC fault-injection rules (ubio --fault-rules=...) ────────────
fault_rules_for_tc() {
    case "$1" in
        47) echo "tc47_dup_clear:ClearReq:1:0:0:dup::1" ;;
        48) echo "tc48_dup_inv_ack:InvalidateAck:2:0:0:dup::1" ;;
        49) echo "tc49_dup_inv_ack:InvalidateAck:1:0:0:dup::1" ;;
        110) echo "tc110_drop_clear:ClearReq:1:1:0:drop::1" ;;
        111) echo "tc111_silent_upgrade_drop:UpgradeReq:1:1:0:drop::1" ;;
        117) echo "tc117_reorder_clear:ClearReq:0:1:0:reorder:100000:1" ;;
        118) echo "tc118_drop:ClearReq:0:1:0x10018011800:drop::1;tc118_delay:ClearReq:0:1:0x10018011900:delay:100000:1" ;;
        119) echo "tc119_drop:ClearReq:0:1:0x10018011900:drop::1;tc119_dup:ClearReq:0:1:0x10018011940:dup::1;tc119_delay:ClearReq:0:1:0x10018011980:delay:100000:1" ;;
        *)  echo "" ;;
    esac
}

# ── Per-TC extra ubio args (ResidentDir params, etc.) ──────────────
ubio_extra_args_for_tc() {
    case "$1" in
        116) echo "--bloom-bytes=512 --sram-bytes=6144 --ways=2 ${UBCC_POLICY:+--dir-overflow-policy=$UBCC_POLICY} ${UBCC_OPTS:-}" ;;
        120)
            case "${EP_PERF_PROFILE:-optimized}" in
                naive|baseline) echo "--bloom-bytes=512 --sram-bytes=5000 --ways=2 --set-bits=2 --dir-overflow-policy=naive --batch-rs=0 ${UBCC_OPTS:-}" ;;
                spill-noopt) echo "--bloom-bytes=512 --sram-bytes=5000 --ways=2 --set-bits=2 --dir-overflow-policy=spill --batch-rs=0 ${UBCC_OPTS:-}" ;;
                optimized|*) echo "--bloom-bytes=512 --sram-bytes=5000 --ways=2 --set-bits=2 --dir-overflow-policy=${UBCC_POLICY:-spill} --batch-rs=1 ${UBCC_OPTS:-}" ;;
            esac
            ;;
        121)
            case "${EP_PERF_PROFILE:-optimized}" in
                naive|baseline) echo "--bloom-bytes=512 --sram-bytes=5000 --ways=2 --set-bits=2 --dir-overflow-policy=naive --batch-rs=0 ${UBCC_OPTS:-}" ;;
                spill-noopt) echo "--bloom-bytes=512 --sram-bytes=5000 --ways=2 --set-bits=2 --dir-overflow-policy=spill --batch-rs=0 ${UBCC_OPTS:-}" ;;
                optimized|*) echo "--bloom-bytes=512 --sram-bytes=5000 --ways=2 --set-bits=2 --dir-overflow-policy=${UBCC_POLICY:-spill} --batch-rs=1 ${UBCC_OPTS:-}" ;;
            esac
            ;;
        122|123)
            case "${EP_PERF_PROFILE:-optimized}" in
                naive|baseline) echo "--bloom-bytes=512 --sram-bytes=6144 --ways=2 --dir-overflow-policy=naive --batch-rs=0 ${UBCC_OPTS:-}" ;;
                spill-noopt) echo "--bloom-bytes=512 --sram-bytes=6144 --ways=2 --dir-overflow-policy=spill --batch-rs=0 ${UBCC_OPTS:-}" ;;
                optimized|*) echo "--bloom-bytes=512 --sram-bytes=6144 --ways=2 --dir-overflow-policy=${UBCC_POLICY:-spill} --batch-rs=1 ${UBCC_OPTS:-}" ;;
            esac
            ;;
        124)
            case "${EP_PERF_PROFILE:-optimized}" in
                naive|baseline|spill-noopt) echo "--batch-rs=0 ${UBCC_OPTS:-}" ;;
                optimized|*) echo "--batch-rs=1 ${UBCC_OPTS:-}" ;;
            esac
            ;;
        125|126|127|128|129)
            case "${EP_PERF_PROFILE:-spill-noopt}" in
                optimized) echo "--bloom-bytes=512 --sram-bytes=6144 --ways=1 --dir-overflow-policy=spill --batch-rs=1 ${UBCC_OPTS:-}" ;;
                *)         echo "--bloom-bytes=512 --sram-bytes=6144 --ways=1 --dir-overflow-policy=spill --batch-rs=0 ${UBCC_OPTS:-}" ;;
            esac
            ;;
        130|135|136|137|138|139|141)
            case "${EP_PERF_PROFILE:-spill-noopt}" in
                naive|baseline) echo "--bloom-bytes=${UBCC_BLOOM_BYTES:-512} --sram-bytes=5000 --ways=2 --set-bits=2 --dir-overflow-policy=naive --batch-rs=0 ${UBCC_OPTS:-}" ;;
                optimized) echo "--bloom-bytes=${UBCC_BLOOM_BYTES:-512} --sram-bytes=5000 --ways=2 --set-bits=2 --dir-overflow-policy=spill --batch-rs=1 ${UBCC_OPTS:-}" ;;
                *) echo "--bloom-bytes=${UBCC_BLOOM_BYTES:-512} --sram-bytes=5000 --ways=2 --set-bits=2 --dir-overflow-policy=spill --batch-rs=0 ${UBCC_OPTS:-}" ;;
            esac
            ;;
        142|143|144|145|146|147)
            # Database workloads use a 512-entry, 1-way ResidentDir and stream
            # 768 maintenance lines around a repeatedly used database hot set.
            case "${EP_PERF_PROFILE:-spill-noopt}" in
                naive|baseline) echo "--bloom-bytes=128 --sram-bytes=4352 --ways=1 --set-bits=0 --dir-overflow-policy=naive --batch-rs=0 ${UBCC_OPTS:-}" ;;
                optimized) echo "--bloom-bytes=128 --sram-bytes=4352 --ways=1 --set-bits=0 --dir-overflow-policy=spill --batch-rs=1 ${UBCC_OPTS:-}" ;;
                *) echo "--bloom-bytes=128 --sram-bytes=4352 --ways=1 --set-bits=0 --dir-overflow-policy=spill --batch-rs=0 ${UBCC_OPTS:-}" ;;
            esac
            ;;
        140)
            case "${EP_PERF_PROFILE:-spill-noopt}" in
                optimized) echo "--batch-rs=1 ${UBCC_OPTS:-}" ;;
                *) echo "--batch-rs=0 ${UBCC_OPTS:-}" ;;
            esac
            ;;
        131|132|133|134)
            # ── Phase A1: Unambiguous policy selection ──
            # TC131-134 overflow policy is controlled by UBCC_POLICY env var
            # (not EP_PERF_PROFILE). Valid values: spill (default), naive.
            # Use UBCC_POLICY=naive to select naive-evict; spill otherwise.
            local policy="${UBCC_POLICY:-spill}"
            local bloom_bytes=61440
            if [ "$policy" = "naive" ]; then
                bloom_bytes=0
            fi
            # Emit manifest marker for verifier consumption (stdout + log)
            printf "[RUNNER-MANIFEST] TC%d policy=%s bloom_bytes=%d sram_bytes=524288\n" \
                "$1" "$policy" "$bloom_bytes" >&2
            echo "--bloom-bytes=$bloom_bytes --sram-bytes=524288 --ways=0 --set-bits=0 --dir-overflow-policy=$policy --batch-rs=0 ${UBCC_OPTS:-}"
            ;;
        200)
            # Phase A3: tiny naive ResidentDir for capacity-pressure recall test
            echo "--bloom-bytes=0 --sram-bytes=64 --ways=1 --set-bits=0 --dir-overflow-policy=naive --batch-rs=0 ${UBCC_OPTS:-}"
            ;;
        201)
            # Phase A5: tiny spill ResidentDir + backstore for durability test.
            # sram-bytes must exceed bloom+index (128+4096=4224) to avoid underflow.
            echo "--bloom-bytes=128 --sram-bytes=4352 --ways=1 --set-bits=3 --dir-overflow-policy=spill --batch-rs=0 ${UBCC_OPTS:-}"
            ;;
        202)
            # Phase C1: spill push-grant authoritative home-data test
            echo "--bloom-bytes=128 --sram-bytes=4352 --ways=1 --set-bits=0 --dir-overflow-policy=spill --batch-rs=0 ${UBCC_OPTS:-}"
            ;;
        203)
            # Phase 5: H64 spill/onload regression. Hash collision and
            # tombstone semantics are tested directly by the focused Host test.
            echo "--bloom-bytes=128 --sram-bytes=4352 --ways=1 --set-bits=0 --dir-overflow-policy=spill --batch-rs=0 ${UBCC_OPTS:-}"
            ;;
        210|211|212|213|214|215|216|217|218|219|220|221)
            case "${EP_PERF_PROFILE:-optimized}" in
                naive) echo "--bloom-bytes=128 --sram-bytes=4352 --ways=1 --set-bits=0 --dir-overflow-policy=naive --batch-rs=0 ${UBCC_OPTS:-}" ;;
                spill-noopt) echo "--bloom-bytes=128 --sram-bytes=4352 --ways=1 --set-bits=0 --dir-overflow-policy=spill --batch-rs=0 ${UBCC_OPTS:-}" ;;
                optimized|*) echo "--bloom-bytes=128 --sram-bytes=4352 --ways=1 --set-bits=0 --dir-overflow-policy=spill --batch-rs=1 ${UBCC_OPTS:-}" ;;
            esac
            ;;
        98)  echo "--ways=1" ;;
        *)   echo "" ;;
    esac
}

# ─── Lookup json module command (placeholder substitution) ────────────
# expand_cmd <module_id> <fault_rules> <ubio_extra_args> [node_outdir]
# Env: runtime paths used to substitute runner-specific placeholders.
expand_cmd() {
    local mod_id="$1"; local frules="$2"; local uextra="$3"; local node_od="${4:-}"
    NODE_OUTDIR="$node_od" python3 - "$JSON" "$mod_id" "$frules" "$uextra" <<'PY'
import json, os, shlex, sys
cfg_path, mod_id, frules, uextra = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4]
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(cfg_path)))
c = json.load(open(cfg_path))
mod = next((m for m in c["modules"] if m["id"]==mod_id), None)
if not mod:
    sys.exit(2)
def r(s):
    s = s.replace("{root}", ROOT)
    s = s.replace("{gem5_bin}", os.path.join(ROOT,"gem5/build/ARM/gem5.opt"))
    s = s.replace("{ubio_bin}", os.path.join(ROOT,"build/bin/ubio"))
    s = s.replace("{nsim_bin}", os.path.join(ROOT,"build/bin/networksim"))
    s = s.replace("{test_e2e}", os.path.join(ROOT,"tests/e2e/test_e2e.py"))
    s = s.replace("{workload}", os.environ["RUN_WORKLOAD"])
    s = s.replace("{topo_json}", os.environ["RUN_TOPO_JSON"])
    s = s.replace("{node_outdir}", os.environ.get("NODE_OUTDIR",""))
    # Fault rules are a single CLI argument and may contain ';' separators.
    # Quote them before the runner's eval-based launch wrapper sees the command.
    s = s.replace("{fault_rules_args}", shlex.quote(frules) if frules else "")
    s = s.replace("{ubio_extra_args}", uextra)
    return s
print(r(mod["cmd"]))
PY
}

# ─── per-TC run ─────────────────────────────────────────────────────
LOG_BASE="${LOG_BASE:-$ROOT_DIR/logs/$(date +%Y%m%d_%H%M%S)_${TOPO_KIND}_${RUN_ID}}"
mkdir -p "$LOG_BASE" "$RUN_DIR" "$IPC_DIR"
export UBCC_IPC_DIR="$IPC_DIR"
export RUN_WORKLOAD="$WORKLOAD"
export RUN_TOPO_JSON="$TOPO_JSON"

# Kill any leftover infra from a previous TC / abort.
_kill_pid_tree() {
    # Commands are launched through a shell wrapper so killing only the wrapper
    # can leave its eval-launched gem5/UBIO child alive. Walk only descendants
    # of the explicitly recorded PID; never perform a name-based kill.
    local pid="$1" child
    [ -n "$pid" ] || return
    for child in $(pgrep -P "$pid" 2>/dev/null || true); do
        _kill_pid_tree "$child"
    done
    kill -TERM "$pid" 2>/dev/null || true
    sleep 0.1
    kill -KILL "$pid" 2>/dev/null || true
}

_kill_infra() {
    # Every PID is recorded by this runner for the current TC. Never use a
    # name-based kill here: another user run may share the host.
    for pid in ${GEM5_PIDS:-} ${UBIO_PIDS:-} ${NSIM_PID:-} ${SUPERVISOR_PID:-}; do
        _kill_pid_tree "$pid"
    done
    if [ -n "${MEMORY_MONITOR_PID:-}" ]; then
        kill "$MEMORY_MONITOR_PID" 2>/dev/null || true
        MEMORY_MONITOR_PID=""
    fi
    if [ -n "${SUPERVISOR_PID:-}" ]; then
        kill "$SUPERVISOR_PID" 2>/dev/null || true
        SUPERVISOR_PID=""
    fi
    for pid in ${GEM5_PIDS:-} ${UBIO_PIDS:-} ${NSIM_PID:-}; do
        wait "$pid" 2>/dev/null || true
    done
    sleep 0.3
    GEM5_PIDS=""; UBIO_PIDS=""; NSIM_PID=""
}
_record_runner_signal() {
    local signal=$1
    printf '[runner] signal=%s pid=%s tc=%s\n' "$signal" "$$" "${CURRENT_TC:-none}" \
        >>"${LOG_BASE:-/tmp}/runner_signals.log"
}
trap '_record_runner_signal EXIT; _kill_infra' EXIT
trap '_record_runner_signal HUP; exit 129' HUP
trap '_record_runner_signal INT; exit 130' INT
trap '_record_runner_signal TERM; exit 143' TERM

_start_memory_monitor() {
    local tc=$1
    local interval="${E2E_MEMORY_MONITOR_SEC:-0}"
    [ "$interval" -gt 0 ] 2>/dev/null || return

    local log="$LOG_BASE/memory_tc${tc}.log"
    (
        while true; do
            date '+[MEMORY] %FT%T%z'
            free -b
            ps -eo pid=,ppid=,rss=,vsz=,comm= | \
                while read -r pid ppid rss vsz comm; do
                    case "$comm" in
                        gem5.opt|ubio|networksim)
                            printf '[MEMORY-PROC] pid=%s ppid=%s rss_kb=%s vsz_kb=%s cmd=%s\n' \
                                "$pid" "$ppid" "$rss" "$vsz" "$comm"
                            ;;
                    esac
                done
            sleep "$interval"
        done
    ) >>"$log" 2>&1 &
    MEMORY_MONITOR_PID=$!
    echo "[monitor] memory sampling every ${interval}s -> $log"
}

# Return the greatest recent UBIO simulation tick.  Guest phase markers are
# sparse during long spill streams, so simout byte growth alone is not a
# liveness signal; protocol tick movement is.  Only inspect each log tail to
# keep the supervisor's own work bounded as logs grow.
_aggregate_protocol_tick() {
    local max_tick=0
    local log tick
    for nid in $(seq 0 $((NUM_NODES-1))); do
        for sid in $(seq 0 $((NUM_SOCKETS-1))); do
            log="$LOG_BASE/ubio_n${nid}_s${sid}/stderr.log"
            [ -f "$log" ] || continue
            tick=$(perl -e '
                $f = shift;
                open(my $fh, "<", $f) or exit;
                $n = -s $fh;
                seek($fh, $n > 1048576 ? $n - 1048576 : 0, 0);
                local $/;
                $s = <$fh>;
                while ($s =~ /tick=(\d+)/g) { $last = $1; }
                print $last // 0;
            ' "$log")
            if [ "$tick" -gt "$max_tick" ] 2>/dev/null; then
                max_tick=$tick
            fi
        done
    done
    printf '%s\n' "$max_tick"
}

# ── Supervisor: opt-in long-run watchdog ───────────────────────────
# Writes PID manifest, monitors liveness/progress/log-size/disk.
# On fault: writes reason to status file, kills CURRENT_TC PIDs + self;
# never uses pkill.  Returns non-zero to signal runner failure.
_supervisor_start() {
    local tc="$1"
    local m5outdir="$2"
    local num_nodes="$3"
    local manifest="$LOG_BASE/supervisor_manifest_tc${tc}.txt"
    local status_file="$LOG_BASE/supervisor_status_tc${tc}.txt"
    local gem5_pids="$GEM5_PIDS"
    local ubio_pids="$UBIO_PIDS"
    local nsim_pid="$NSIM_PID"

    # Write PID manifest
    {
        echo "# Supervisor manifest TC${tc} $(date -Iseconds)"
        echo "RUNNER_PID=$$"
        echo "NSIM_PID=$nsim_pid"
        echo "GEM5_PIDS=$gem5_pids"
        echo "UBIO_PIDS=$ubio_pids"
        echo "NUM_NODES=$num_nodes"
        echo "LOG_BASE=$LOG_BASE"
        echo "M5OUTDIR=$m5outdir"
        echo "LOG_CEIL_GB=$EP_SUPERVISOR_LOG_CEIL_GB"
        echo "DISK_FREE_GB=$EP_SUPERVISOR_DISK_FREE_GB"
        echo "INTERVAL=$EP_SUPERVISOR_INTERVAL"
        echo "PROGRESS_STALL_SEC=$EP_SUPERVISOR_PROGRESS_STALL_SEC"
        echo "TRACE_PERF=$EP_TRACE_PERF first_n=$EP_TRACE_PERF_FIRST_N every=$EP_TRACE_PERF_EVERY max=$EP_TRACE_PERF_MAX"
        echo "PORT_HWM=$EP_PORT_HWM NSIM_MAX_PENDING=$EP_NSIM_MAX_PENDING"
    } > "$manifest"

    # Start background monitor
    (
        local interval="$EP_SUPERVISOR_INTERVAL"
        local ceil_bytes=$((EP_SUPERVISOR_LOG_CEIL_GB * 1073741824))
        local floor_bytes=$((EP_SUPERVISOR_DISK_FREE_GB * 1073741824))
        local prev_guest_progress=-1
        local prev_protocol_tick=-1
        local guest_stall_count=0
        local protocol_stall_count=0
        local stall_limit=$((EP_SUPERVISOR_PROGRESS_STALL_SEC / interval))
        [ "$stall_limit" -gt 0 ] 2>/dev/null || stall_limit=1

        while true; do
            sleep "$interval"

            # ── 1. Liveness: live gem5 plus clean completed peers ─
            local alive_count=0
            local completed_count=0
            for pid in $gem5_pids; do
                local state
                state=$(ps -o stat= -p "$pid" 2>/dev/null || true)
                state=${state#${state%%[![:space:]]*}}
                case "$state" in
                    Z*|"") completed_count=$((completed_count + 1)) ;;
                    *) if [ -n "$state" ]; then alive_count=$((alive_count + 1)); fi ;;
                esac
            done
            local gem5_status gem5_code
            for gem5_status in "$LOG_BASE"/child_status_tc${tc}/gem5_node*.exit; do
                [ -f "$gem5_status" ] || continue
                gem5_code=$(tr -d '[:space:]' <"$gem5_status")
                if [ "$gem5_code" != "0" ]; then
                    local ts; ts=$(date +%s)
                    echo "FAULT ${ts} gem5_exit: $(basename "$gem5_status")=$gem5_code" >> "$status_file"
                    echo "[supervisor] FAULT: $(basename "$gem5_status") exited $gem5_code"
                    for pid in $gem5_pids $ubio_pids $nsim_pid; do
                        kill -9 "$pid" 2>/dev/null || true
                    done
                    exit 1
                fi
            done
            # All gem5 wrappers exiting cleanly means the foreground runner is
            # about to collect statuses and coordinate UBIO/networksim teardown.
            if [ "$alive_count" -eq 0 ]; then
                local ts; ts=$(date +%s)
                echo "COMPLETE ${ts} all_gem5_exited; runner collecting statuses" >> "$status_file"
                exit 0
            fi

            # ── 2. Progress: either guest output or protocol tick movement
            # keeps the generic watchdog alive. Profile-specific runners may
            # inspect both fields to distinguish guest stalls from long fault
            # recovery or spill streams without killing valid workloads.
            local current_guest_progress=0
            for nid in $(seq 0 $((num_nodes - 1))); do
                local pf="$m5outdir/node${nid}/simout_n${nid}"
                if [ -f "$pf" ]; then
                    current_guest_progress=$((current_guest_progress + $(stat -c %s "$pf" 2>/dev/null || echo 0)))
                fi
            done
            local current_protocol_tick
            current_protocol_tick=$(_aggregate_protocol_tick)
            if [ "$current_guest_progress" -ne "$prev_guest_progress" ] || \
               [ "$current_protocol_tick" -gt "$prev_protocol_tick" ]; then
                prev_guest_progress="$current_guest_progress"
                prev_protocol_tick="$current_protocol_tick"
                guest_stall_count=0
            else
                guest_stall_count=$((guest_stall_count + 1))
                if [ "$guest_stall_count" -ge "$stall_limit" ]; then
                    local ts; ts=$(date +%s)
                    echo "FAULT ${ts} progress_stall: guest_bytes=${current_guest_progress} protocol_tick=${current_protocol_tick} for $((guest_stall_count * interval))s" >> "$status_file"
                    echo "[supervisor] FAULT: no guest or protocol tick progress for $((guest_stall_count * interval))s"
                    for pid in $gem5_pids $ubio_pids $nsim_pid; do
                        kill -9 "$pid" 2>/dev/null || true
                    done
                    exit 1
                fi
            fi
            if [ "$current_protocol_tick" -gt "$prev_protocol_tick" ]; then
                protocol_stall_count=0
            else
                protocol_stall_count=$((protocol_stall_count + 1))
            fi

            # ── 3. Log directory size check ───────────────────────
            local log_size
            log_size=$(du -sb "$LOG_BASE" 2>/dev/null | cut -f1 || echo 0)
            if [ "$log_size" -gt "$ceil_bytes" ]; then
                local ts; ts=$(date +%s)
                echo "FAULT ${ts} log_size: ${log_size} bytes > ceil ${ceil_bytes} bytes (${EP_SUPERVISOR_LOG_CEIL_GB}GiB)" >> "$status_file"
                echo "[supervisor] FAULT: log dir ${log_size} > ${EP_SUPERVISOR_LOG_CEIL_GB}GiB ceiling"
                for pid in $gem5_pids $ubio_pids $nsim_pid; do
                    kill -9 "$pid" 2>/dev/null || true
                done
                exit 1
            fi

            # ── 4. Disk free space check ──────────────────────────
            local disk_free
            disk_free=$(df -B1 "$LOG_BASE" 2>/dev/null | tail -1 | awk '{print $4}')
            if [ -n "$disk_free" ] && [ "$disk_free" -lt "$floor_bytes" ]; then
                local ts; ts=$(date +%s)
                echo "FAULT ${ts} disk_free: ${disk_free} bytes < floor ${floor_bytes} bytes (${EP_SUPERVISOR_DISK_FREE_GB}GiB)" >> "$status_file"
                echo "[supervisor] FAULT: disk free ${disk_free} < ${EP_SUPERVISOR_DISK_FREE_GB}GiB floor"
                for pid in $gem5_pids $ubio_pids $nsim_pid; do
                    kill -9 "$pid" 2>/dev/null || true
                done
                exit 1
            fi

            # ── Heartbeat (only to status file, not stdout) ───────
            local ts; ts=$(date +%s)
            echo "OK ${ts} alive=${alive_count}/${num_nodes} completed=${completed_count} guest_bytes=${current_guest_progress} guest_stall_sec=$((guest_stall_count * interval)) protocol_tick=${current_protocol_tick} protocol_stall_sec=$((protocol_stall_count * interval)) log_size=${log_size} disk_free=${disk_free:-na}" >> "$status_file"
        done
    ) &
    SUPERVISOR_PID=$!
    echo "[supervisor] started pid=$SUPERVISOR_PID manifest=$manifest interval=${EP_SUPERVISOR_INTERVAL}s"
}

_supervisor_stop() {
    if [ -n "${SUPERVISOR_PID:-}" ]; then
        kill "$SUPERVISOR_PID" 2>/dev/null || true
        SUPERVISOR_PID=""
    fi
}

run_tc() {
    local tc=$1
    CURRENT_TC=$tc
    _kill_infra  # ensure clean state before each TC

    # TC98 fix: per-TC timeout override.  High-contention tests need much
    # longer than the default 600s because PDES serialization is inherent.
    local TC_TIMEOUT="$TIMEOUT_SEC"
    case "$tc" in
        98) TC_TIMEOUT="${TIMEOUT_SEC_TC98:-1500}" ;;  # floor 1500s, overridable
        128) TC_TIMEOUT="${TIMEOUT_SEC_TC128:-1800}" ;; # full cache sweep + onload
        131) TC_TIMEOUT="${TIMEOUT_SEC_TC131:-7200}" ;;
        132) TC_TIMEOUT="${TIMEOUT_SEC_TC132:-7200}" ;;
        133) TC_TIMEOUT="${TIMEOUT_SEC_TC133:-7200}" ;;
        134) TC_TIMEOUT="${TIMEOUT_SEC_TC134:-7200}" ;;
    esac
    # Always respect a higher value passed via TIMEOUT_SEC env var
    if [ "$TIMEOUT_SEC" -gt "$TC_TIMEOUT" ] 2>/dev/null; then
        TC_TIMEOUT="$TIMEOUT_SEC"
    fi

    local m5base="$RUN_DIR/tc${tc}"
    local m5outdir="$m5base/m5out"
    local child_status_dir="$LOG_BASE/child_status_tc${tc}"
    rm -rf "$m5base"; mkdir -p "$m5outdir"
    rm -rf "$child_status_dir"; mkdir -p "$child_status_dir"

    echo ""
    echo "=== TC${tc} (topo=$TOPO_KIND, ${NUM_NODES}nodes x ${NUM_SOCKETS}sockets) ==="

    # 1. Compile workload into this run's private ELF path.
    NUM_NODES="$NUM_NODES" NUM_SOCKETS="$NUM_SOCKETS" \
        WORKLOAD_OUT="$WORKLOAD" bash "$ROOT_DIR/scripts/compile_workload.sh" "$tc" >/dev/null 2>&1 \
        || { echo "  TC${tc} COMPILE FAILED"; return 1; }

    # 2. Generate networksim topo.json (full mesh, --nodes/--sockets from JSON)
    python3 "$ROOT_DIR/scripts/gen_topo.py" --nodes "$NUM_NODES" --sockets "$NUM_SOCKETS" --out "$TOPO_JSON" >/dev/null 2>&1
    # Clean only this run's IPC endpoints. Other runs use distinct directories.
    rm -rf "$IPC_DIR" 2>/dev/null || true
    mkdir -p "$IPC_DIR"

    # 3. Start networksim (must bind before ubio connects)
    local nsim_pid_file="$child_status_dir/networksim.pid"
    rm -f "$nsim_pid_file"
    echo "[launch] networksim (NMOD=$NMOD)"
    (
      set +e
      "$NSIM_BIN" "$TOPO_JSON" >"$LOG_BASE/nsim_tc${tc}.log" 2>&1 &
      local_nsim_child=$!
      printf '%s\n' "$local_nsim_child" >"$nsim_pid_file"
      wait "$local_nsim_child"
      status=$?
      printf '%s\n' "$status" >"$child_status_dir/networksim.exit"
      exit "$status"
    ) &
    NSIM_PID=$!
    NSIM_CHILD_PID=""
    for _ in $(seq 1 50); do
        if [ -f "$nsim_pid_file" ]; then
            NSIM_CHILD_PID=$(tr -d '[:space:]' <"$nsim_pid_file")
            break
        fi
        sleep 0.1
    done
    if [ -z "$NSIM_CHILD_PID" ]; then
        echo "[launch] networksim failed to report child PID"
        _kill_infra
        return 1
    fi
    sleep 1

    # 4. Start N gem5 nodes, wait until each binds its ports (STEP5 marker)
    GEM5_PIDS=""; local gem5_arr=()
    for nid in $(seq 0 $((NUM_NODES-1))); do
        local gdir="$LOG_BASE/gem5_tc${tc}_node${nid}"
        local node_od="$m5outdir/node${nid}"
        mkdir -p "$gdir" "$node_od"
        local cmd
        cmd="$(expand_cmd gem5_${nid} '' '' "$node_od")"
        # Optional per-node gem5 tracing for long-running E2E diagnosis.
        # Keep the debug stream separate from stderr so runner diagnostics stay usable.
        if [ -n "${GEM5_DEBUG_FLAGS:-}" ]; then
            local debug_args="--debug-flags=${GEM5_DEBUG_FLAGS} --debug-file=$gdir/gem5_debug.log"
            if [ -n "${GEM5_DEBUG_START:-}" ]; then
                debug_args="$debug_args --debug-start=${GEM5_DEBUG_START}"
            fi
            cmd="$GEM5_BIN $debug_args${cmd#"$GEM5_BIN"}"
        fi
        if [ "$tc" = "130" ] || [ "$tc" = "132" ] || [ "$tc" = "133" ] || [ "$tc" = "134" ] || [ "$tc" = "141" ] ||
           { [ "$tc" -ge 135 ] && [ "$tc" -le 139 ]; } ||
           { [ "$tc" -ge 142 ] && [ "$tc" -le 147 ]; }; then
            # These tests isolate directory policy; do not mix protocol optimizations.
            case "${EP_PERF_PROFILE:-spill-noopt}" in
                optimized) cmd="$cmd --silent-upgrade=1 --direct-fwd=0 --ubcc-batch-rs=1" ;;
                *)         cmd="$cmd --silent-upgrade=0 --direct-fwd=0 --ubcc-batch-rs=0" ;;
            esac
        elif [ "$tc" = "131" ]; then
            # TC131 is the capacity/latency comparison workload.  The baseline
            # is naive with every latency optimization disabled; optimized uses
            # spill and enables the latency optimization profile.
            case "${EP_PERF_PROFILE:-baseline}" in
                optimized) cmd="$cmd --silent-upgrade=1 --direct-fwd=0 --ubcc-batch-rs=1" ;;
                *)         cmd="$cmd --silent-upgrade=0 --direct-fwd=0 --ubcc-batch-rs=0" ;;
            esac
        elif [ "$tc" = "120" ] || [ "$tc" = "121" ] || [ "$tc" = "122" ] || [ "$tc" = "123" ] || [ "$tc" = "124" ] || [ "$tc" = "140" ]; then
            local default_profile=optimized
            if [ "$tc" = "140" ]; then default_profile=spill-noopt; fi
            case "${EP_PERF_PROFILE:-$default_profile}" in
                baseline|spill-noopt)
                    cmd="$cmd --silent-upgrade=0 --direct-fwd=0 --ubcc-batch-rs=0"
                    ;;
                optimized|*)
                    cmd="$cmd --silent-upgrade=1 --direct-fwd=0 --ubcc-batch-rs=1"
                    ;;
            esac
        fi
        # Explicit experiment-only gem5 flags, for example
        # EP_GEM5_OPTS='--silent-upgrade=1'. Normal test profiles above remain
        # authoritative unless this variable is intentionally set by a runner.
        if [ -n "${EP_GEM5_OPTS:-}" ]; then
            cmd="$cmd ${EP_GEM5_OPTS}"
        fi
        # Phase 0: propagate metadata DRAM capacity to gem5 config
        cmd="$cmd --ubcc_metadata_size=${UBCC_METADATA_SIZE}"
        echo "[launch] gem5 node=$nid (outdir=$node_od)"
        ( set +e; eval "$cmd" 2>"$gdir/stderr.log" >"$gdir/stdout.log"; status=$?; \
          printf '%s\n' "$status" >"$child_status_dir/gem5_node${nid}.exit"; exit "$status" ) &
        local pid=$!
        gem5_arr+=($pid)
        GEM5_PIDS="$GEM5_PIDS $pid"
    done

    # Wait for STEP5 Port enabled (NUM_SOCKETS of them per node)
    echo "[launch] waiting for NUM_NODES=$NUM_NODES gem5 to bind (sockets=$NUM_SOCKETS)..."
    for nid in $(seq 0 $((NUM_NODES-1))); do
        local gout="$LOG_BASE/gem5_tc${tc}_node${nid}/stdout.log"
        local bound=0
        for tries in $(seq 1 300); do    # up to 300s wait (8-node init takes time)
            if [ "$(grep -c 'STEP5.*Port enabled' "$gout" 2>/dev/null)" -ge "$NUM_SOCKETS" ]; then
                bound=1; break
            fi
            if ! kill -0 ${gem5_arr[$nid]} 2>/dev/null; then
                echo "[launch] gem5 node=$nid exited before binding!"
                _kill_infra
                return 1
            fi
            sleep 1
        done
        [ $bound -eq 1 ] && echo "[launch]   node=$nid bound" || {
            echo "[launch] node=$nid bind TIMEOUT"
            _kill_infra
            return 1
        }
    done

    # 5. Start N*K ubio processes (plane = node*K + socket)
    UBIO_PIDS=""
    local frules; frules="$(fault_rules_for_tc "$tc")"
    local frargs=""
    [ -n "$frules" ] && frargs="--fault-rules=$frules"
    [ -n "$frules" ] && echo "[launch] fault rules (TC${tc}): $frules"
    local uextra; uextra="$(ubio_extra_args_for_tc "$tc")"
    # Phase 0: propagate metadata DRAM capacity to every ubio
    uextra="$uextra --metadata-dram-bytes=${UBCC_METADATA_SIZE}"
    [ -n "$uextra" ] && echo "[launch] ubio extra args (TC${tc}): $uextra"
    for nid in $(seq 0 $((NUM_NODES-1))); do
        for sid in $(seq 0 $((NUM_SOCKETS-1))); do
            local mod_id="ubio_${nid}_s${sid}"
            local cmd
            if python3 -c "import json,sys;sys.exit(0 if any(m['id']==sys.argv[1] for m in json.load(open('$JSON'))['modules']) else 1)" "$mod_id" 2>/dev/null; then
                cmd="$(expand_cmd "$mod_id" "$frargs" "$uextra")"
            else
                cmd="$(expand_cmd "ubio_${nid}" "$frargs" "$uextra")"
            fi
            local logdir="$LOG_BASE/ubio_n${nid}_s${sid}"
            mkdir -p "$logdir"
            ( set +e; eval "$cmd" 2>"$logdir/stderr.log" >"$logdir/stdout.log"; status=$?; \
              printf '%s\n' "$status" >"$child_status_dir/ubio_n${nid}_s${sid}.exit"; exit "$status" ) &
            UBIO_PIDS="$UBIO_PIDS $!"
        done
    done
    local n_ubio; n_ubio=$(echo $UBIO_PIDS | wc -w)
    echo "[launch] $n_ubio ubio (${NUM_NODES}x${NUM_SOCKETS}) + $NUM_NODES gem5 running"
    _start_memory_monitor "$tc"

    # 6b. Supervisor: opt-in long-run watchdog (EP_SUPERVISOR=1)
    if [ "${EP_SUPERVISOR:-0}" = "1" ]; then
        _supervisor_start "$tc" "$m5outdir" "$NUM_NODES"
    fi

    # 6. Wait for all gem5 processes to finish (or timeout)
    local waited=0
    local progress_size=-1
    local progress_waited=0
    local progress_watchdog="${PROGRESS_WATCHDOG_SEC:-0}"
    while true; do
        local any=0
        for pid in $GEM5_PIDS; do
            # A completed child remains a zombie until the wait below reaps it.
            # kill -0 succeeds for zombies, so do not mistake one for a running
            # gem5 process and leave UBIO/networksim running indefinitely.
            if kill -0 "$pid" 2>/dev/null; then
                local state
                state=$(ps -o stat= -p "$pid" 2>/dev/null || true)
                state=${state#${state%%[![:space:]]*}}
                case "$state" in
                    Z*) ;;
                    *) any=1 ;;
                esac
            fi
        done
        [ $any -eq 0 ] && break
        sleep 1; waited=$((waited + 1))
        if [ "$progress_watchdog" -gt 0 ] 2>/dev/null; then
            local current_size=0
            # A node may finish its guest phase while peers are still doing
            # their work. Watch the aggregate output of every node, not node0
            # alone, so a valid asymmetric workload is not killed mid-run.
            for nid in $(seq 0 $((NUM_NODES-1))); do
                local progress_file="$m5outdir/node${nid}/simout_n${nid}"
                if [ -f "$progress_file" ]; then
                    current_size=$((current_size + $(stat -c %s "$progress_file")))
                fi
            done
            # Some workloads spend long intervals filling/spilling before a
            # guest printf. Treat bounded protocol-log growth as progress too;
            # without it a valid H64 backstore run is killed mid-transaction.
            for nid in $(seq 0 $((NUM_NODES-1))); do
                for sid in $(seq 0 $((NUM_SOCKETS-1))); do
                    local protocol_log="$LOG_BASE/ubio_n${nid}_s${sid}/stderr.log"
                    if [ -f "$protocol_log" ]; then
                        current_size=$((current_size + $(stat -c %s "$protocol_log")))
                    fi
                done
            done
            if [ "$current_size" -ne "$progress_size" ]; then
                progress_size="$current_size"
                progress_waited=0
            else
                progress_waited=$((progress_waited + 1))
                if [ "$progress_waited" -ge "$progress_watchdog" ]; then
                    echo "  TC${tc} PROGRESS STALL after ${progress_watchdog}s (no guest or protocol output)"
                    _supervisor_stop
                    _kill_infra
                    return 1
                fi
            fi
        fi
        if [ $waited -ge "$TC_TIMEOUT" ]; then
            # TC9 is a negative test: node0 is expected to crash on non-DSM
            # access (Aborted/SIGSEGV). If that crash evidence exists, the
            # test PASSED despite the timeout (other nodes may keep spinning).
            if [ "$tc" -eq 9 ]; then
                local crash_log="$LOG_BASE/gem5_tc${tc}_node0/stderr.log"
                if grep -q "Page table fault when accessing virtual address 0xfffff8000000" \
                    "$crash_log" 2>/dev/null; then
                    echo "  TC${tc} PASSED (expected crash detected)"
                    _supervisor_stop
                    _kill_infra
                    return 0
                fi
                echo "  TC${tc} TIMEOUT (no crash evidence found)"
            else
                echo "  TC${tc} TIMEOUT after ${TC_TIMEOUT}s"
            fi
            _supervisor_stop
            _kill_infra
            return 1
        fi
    done

    # Check exit codes
    local gem5_fail=0
    for pid in $GEM5_PIDS; do
        wait $pid 2>/dev/null || gem5_fail=1
    done

    # Let every UBIO wrapper record its real exit code before shutting down the
    # network simulator. networksim has no all-peer disconnect event, so after
    # UBIO exits the runner explicitly requests its graceful zero-status exit.
    local child_fail=0
    local shutdown_waited=0
    while [ "$shutdown_waited" -lt 15 ]; do
        local child_running=0
        for pid in $UBIO_PIDS; do
            if kill -0 "$pid" 2>/dev/null; then
                local child_state
                child_state=$(ps -o stat= -p "$pid" 2>/dev/null || true)
                child_state=${child_state#${child_state%%[![:space:]]*}}
                case "$child_state" in Z*) ;; *) child_running=1 ;; esac
            fi
        done
        [ "$child_running" -eq 0 ] && break
        sleep 1
        shutdown_waited=$((shutdown_waited + 1))
    done
    if [ "$shutdown_waited" -ge 15 ]; then
        echo "  TC${tc} CHILD SHUTDOWN TIMEOUT"
        child_fail=1
        for pid in $UBIO_PIDS ${NSIM_PID:-}; do kill "$pid" 2>/dev/null || true; done
        sleep 1
    elif [ -n "${NSIM_PID:-}" ]; then
        # Signal the recorded networksim child; its wrapper then reaps it and
        # writes networksim.exit with the simulator's real status.
        kill -TERM "$NSIM_CHILD_PID" 2>/dev/null || true

        shutdown_waited=0
        while [ "$shutdown_waited" -lt 15 ]; do
            if ! kill -0 "$NSIM_PID" 2>/dev/null; then
                break
            fi
            local nsim_state
            nsim_state=$(ps -o stat= -p "$NSIM_PID" 2>/dev/null || true)
            nsim_state=${nsim_state#${nsim_state%%[![:space:]]*}}
            case "$nsim_state" in Z*) break ;; esac
            sleep 1
            shutdown_waited=$((shutdown_waited + 1))
        done
        if [ "$shutdown_waited" -ge 15 ]; then
            echo "  TC${tc} NETWORKSIM SHUTDOWN TIMEOUT"
            child_fail=1
            _kill_pid_tree "$NSIM_PID"
        fi
    fi

    # Reap the wrappers so every managed process has a final status file.
    for pid in $UBIO_PIDS ${NSIM_PID:-}; do wait "$pid" 2>/dev/null || true; done

    local status_file status_code status_count=0
    for status_file in "$child_status_dir"/*.exit; do
        [ -f "$status_file" ] || continue
        status_count=$((status_count + 1))
        status_code=$(tr -d '[:space:]' <"$status_file")
        if [ "$status_code" != "0" ]; then
            echo "  TC${tc} CHILD FAILED: $(basename "$status_file") exit=$status_code"
            child_fail=1
        fi
    done
    local expected_status_count=$((NUM_NODES * NUM_SOCKETS + NUM_NODES + 1))
    if [ "$status_count" -ne "$expected_status_count" ]; then
        echo "  TC${tc} CHILD FAILED: expected ${expected_status_count} exit files, found ${status_count}"
        child_fail=1
    fi

    # All child wrappers are reaped. Stop only auxiliary monitoring here.
    _supervisor_stop
    if [ -n "${MEMORY_MONITOR_PID:-}" ]; then
        kill "$MEMORY_MONITOR_PID" 2>/dev/null || true
        MEMORY_MONITOR_PID=""
    fi
    sleep 0.2

    if [ $gem5_fail -ne 0 ] || [ $child_fail -ne 0 ]; then
        # TC9 is a negative test: node0 must reject the unmapped non-DSM
        # access. The crash can happen before the timeout loop observes it.
        if [ "$tc" -eq 9 ]; then
            local crash_log="$LOG_BASE/gem5_tc${tc}_node0/stderr.log"
            if grep -q "Page table fault when accessing virtual address 0xfffff8000000" \
                "$crash_log" 2>/dev/null; then
                echo "  TC${tc} PASSED (expected crash detected)"
                return 0
            fi
        fi
        echo "  TC${tc} CRASHED (a managed child exited non-zero)"
        return 1
    fi

    # 7. Verify via independent verify.py
    local simouts=()
    for nid in $(seq 0 $((NUM_NODES-1))); do
        local simout="$m5outdir/node${nid}/simout_n${nid}"
        simouts+=("$simout")
        if [ -f "$simout" ]; then
            cp "$simout" "$LOG_BASE/simout_tc${tc}_node${nid}.log" 2>/dev/null || true
        fi
    done
    local faultlogs=()
    for nid in $(seq 0 $((NUM_NODES-1))); do
        for sid in $(seq 0 $((NUM_SOCKETS-1))); do
            faultlogs+=("$LOG_BASE/ubio_n${nid}_s${sid}/stderr.log")
            faultlogs+=("$LOG_BASE/ubio_n${nid}_s${sid}/stdout.log")
        done
    done
    local vlog="$LOG_BASE/verify_tc${tc}.log"
    python3 "$ROOT_DIR/tests/e2e/verify.py" --tc=$tc \
        --simout "${simouts[@]}" --fault-log "${faultlogs[@]}" 2>&1 | tee "$vlog"
    # Last sentinel line decides
    if tail -n1 "$vlog" 2>/dev/null | grep -q ">>> TC${tc} PASSED <<<"; then
        # Persist request issue-to-first-response chains for cross-run latency
        # evaluation.  TRACE-PERF is emitted by gem5, UBIO, and networksim.
        python3 "$ROOT_DIR/scripts/trace2chain.py" "$LOG_BASE" \
            >"$LOG_BASE/trace_chains_tc${tc}.json" 2>/dev/null || true
        echo "  TC${tc} PASSED"
        return 0
    else
        echo "  TC${tc} FAILED"
        return 1
    fi
}

# ── Main ─────────────────────────────────────────────────────────────
[ -x "$GEM5_BIN" ] || { echo "FATAL: $GEM5_BIN not built"; exit 2; }
[ -x "$UBIO_BIN" ] || [ -x "$NSIM_BIN" ] || { echo "FATAL: native binaries not built"; exit 2; }

echo "=== Multi-Process E2E Runner (decoupled, topo=$TOPO_KIND) ==="
echo "Config:  $JSON"
echo "Log base: $LOG_BASE"
echo "Sockets/node: $NUM_SOCKETS  (NMOD=$NMOD)"
echo "Workload: $WORKLOAD  (compiled per-TC; path is constant)"

# These workloads embed a fixed node/socket count and barrier mask. Reject a
# mismatch before compiling or starting any managed process.
required_topology_for_tc() {
    case "$1" in
        135|136|137|138|139|140|141)          printf '%s\n' 1s ;;
        32|33|34|35|39|81)                 printf '%s\n' 2s ;;
        82|90|91|92|93|94|133)             printf '%s\n' 8n1s ;;
        95|96|97|98|99|100|101|134)        printf '%s\n' 8n2s ;;
        210|211|212|213|214|215|216|217|218|219|220|221) printf '%s\n' 2n1s ;;
    esac
}

for tc in "$@"; do
    required_topology="$(required_topology_for_tc "$tc")"
    if [ -n "$required_topology" ] && [ "$TOPO_KIND" != "$required_topology" ]; then
        echo "FATAL: TC$tc requires --$required_topology topology. Re-run with --$required_topology." >&2
        exit 2
    fi
done

PASS=0; FAIL=0
for tc in "$@"; do
    if UBIO_PIDS="" run_tc "$tc"; then PASS=$((PASS+1)); else FAIL=$((FAIL+1)); fi
    # cleanup any stragglers between TCs
    for pid in ${UBIO_PIDS:-} ${NSIM_PID:-}; do kill $pid 2>/dev/null || true; done
done

echo ""
echo "=== Results: $PASS pass, $FAIL fail ==="
echo "Logs: $LOG_BASE"
